# Generated by Django 2.1.4 on 2018-12-20 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='article',
            new_name='description',
        ),
        migrations.AddField(
            model_name='rating',
            name='article',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='user_rating', to='webapp.Article', verbose_name='Статья'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rating',
            name='created_at',
            field=models.DateField(default='2014-09-13', verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rating',
            name='status',
            field=models.CharField(choices=[('excellent', 'excellent'), ('good', 'good'), ('satisfactory', 'satisfactory'), ('bad', 'bad'), ('poor', 'poor')], default='satisfactory', max_length=30, verbose_name='Оценка'),
        ),
    ]
